import { StyleSheet } from "react-native";

export const estilosMisTareasAsignadas = StyleSheet.create({
    contenedorPrincipal: { flex: 1, backgroundColor: '#F8FAFC', paddingHorizontal: 20 },
    headerTop: { marginTop: 20, marginBottom: 20, flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
    tituloHeader: { fontSize: 20, fontWeight: 'bold', color: '#1E293B' },
    operadorHeader: { fontSize: 13, color: '#475569', backgroundColor: '#E2E8F0', padding: 6, borderRadius: 10, fontWeight: '600' },
    card: { backgroundColor: '#FFF', borderRadius: 15, padding: 15, marginBottom: 12, elevation: 2 },
    cardHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
    lugarTexto: { fontSize: 15, fontWeight: 'bold', color: '#334155' },
    divisor: { height: 1, backgroundColor: '#F1F5F9', marginVertical: 10 },
    cardBody: { gap: 4 },
    badge: { fontSize: 12, fontWeight: 'bold', paddingHorizontal: 8, paddingVertical: 3, borderRadius: 8, overflow: 'hidden' },
    badgePendiente: { backgroundColor: '#FEE2E2', color: '#EF4444' },
    badgeProceso: { backgroundColor: '#FEF3C7', color: '#D97706' },
    descripcionTexto: { fontSize: 16, fontWeight: '700', color: '#1E293B', marginVertical: 2 },
    usuarioTexto: { fontSize: 14, color: '#475569' },
    fechaTexto: { fontSize: 13, color: '#64748B', fontStyle: 'italic' },
    botonAccion: { paddingVertical: 12, borderRadius: 10, alignItems: 'center', justifyContent: 'center', elevation: 2 },
    textoBoton: { color: '#FFF', fontWeight: 'bold', fontSize: 14 },
    emptyText: { textAlign: 'center', marginTop: 50, color: '#64748B', fontWeight: '600', fontSize: 14, paddingHorizontal: 20, lineHeight: 20 },
    modalCentrado: { flex: 1, justifyContent: 'center', alignItems: 'center', backgroundColor: 'rgba(0, 0, 0, 0.5)', paddingHorizontal: 20 },
    contenidoModal: { backgroundColor: '#fff', width: '100%', borderRadius: 15, padding: 20, alignItems: 'center', elevation: 5 },
    modalTitulo: { fontSize: 18, fontWeight: 'bold', color: '#1E293B', marginBottom: 5 },
    modalSub: { fontSize: 14, color: '#475569', marginBottom: 15, textAlign: 'center' },
    inputNota: { width: '100%', backgroundColor: '#F8FAFC', borderRadius: 10, padding: 10, borderWidth: 1, borderColor: '#E2E8F0', height: 80, textAlignVertical: 'top', color: '#000' },
    botonModal: { paddingVertical: 12, borderRadius: 8, alignItems: 'center', justifyContent: 'center' },
    tituloSeccion: { fontSize: 14, fontWeight: 'bold', color: '#94A3B8', marginBottom: 15, textTransform: 'uppercase' },
});